spring:
  kafka:
    consumer:
      bootstrap-servers: localhost:9092
      group-id: foo
      kafka-topic: kafka-chat
    producer:
      bootstrap-servers: localhost:9092
      group-id: foo
      kafka-topic: kafka-chat